export default {
    NotEnoughPlayers: "NotEnoughPlayers",
    Play: "Play",
    PlayerConnect: "PlayerConnect",
    Players: "Players",
    GameFull: "GameFull",
    AlreadyRegistered: "AlreadyRegistered",
    CurrentPlayer: "CurrentPlayer",
    AlreadyStarted: "AlreadyStarted",
    StartRound: "StartRound",
    PlayerTurn: "PlayerTurn",
    Pick: "Pick",
    CardPicked: "CardPicked",
    PlayCard: "PlayCard",
    CardPlayed: "CardPlayed",
    PlayChancellorCard: "PlayChancellorCard",
    ChancellorChooseCard: "ChancellorChooseCard",
    ChancellorPlacedCard: "ChancellorPlacedCard",
    PlayPriestCard: "PlayPriestCard",
    ShowTargetCard: "ShowTargetCard",
    Message: "Message",
    RoundEnded: "RoundEnded",
    GameEnded: "GameEnded",
    NumberOfCardsLeft: "NumberOfCardsLeft",
};
